### ISSUE TITLE
Mention 'json-streamer' as alternative?

### ISSUE THREAD

**Issue by thisismydesign** [dgraham/json-stream#4]
Hi David,

I'm the developer of the [json-streamer](https://github.com/thisismydesign/json-streamer) gem which is based on your implementation. It spares the need to create your own callbacks for parsing (such as start_document, end_document, key, value, etc.). I think it's worth a mention as an alternative. Let me know what you think.

Thanks,
Csaba

**Comment by eggie5** [comment]
looks awesome in that it fills exactly my use case: it can replace the simple parse i had to write using `son-stream`'s callbacks!

**Comment by dgraham** [comment]
Neat gem! I'd like to keep the list of alternatives to full JSON parsers, though. The json-streamer gem is a specialized filtering parser, rather than a drop-in replacement for full JSON parsing.

**Comment by thisismydesign** [comment]
It can easily be used as a drop-in replacement the following way: `streamer.get(nesting_level:0)`

There's a note of this in the README but I can also highlight this feature if that's the only reason keeping you.

Either way my reason for asking is to help out others who stumble upon the same issue that I did (hence the gem) and I think this thread can attest that they would find it helpful - even if it involves some amount of clarification about the differences. In light of this would you reconsider?
