### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by UliKuch** [dgraham/json-stream#7]
Hi @dgraham!

Thanks a lot for this gem and your open source work!

I noticed that the latest release for this gem does not include all the the most recent commits -- I am especially missing [this commit](https://github.com/dgraham/json-stream/commit/9b81805999f94b47fbdaa5df6dedf78099446e21). Because this was missing, we were receiving the following exception, probably because of an emoji in the JSON document we were trying to parse: 

```
somethingsomething/gems/json-stream-0.2.1/lib/json/stream/parser.rb:232:in `block in <<':
uninitialized constant JSON::Stream::Parser::Fixnum (NameError)
error('Expected low surrogate pair half') if @stack[-1].is_a?(Fixnum)
```

Using the most recent commit of this gem fixed the error for us

```ruby
gem 'json-stream', github: 'dgraham/json-stream', ref: '63a963e6563652a09a5dc5d11f27a9fc84aea65a'
```

Maybe you could release a new version of this gem? 🙂

**Comment by dgraham** [comment]
I published 0.2.2 today. Thanks for the long overdue reminder.
